### ISSUE TITLE
When will it be open source

### ISSUE THREAD

**Issue by QinZiwen** [Xuanmeng-Zhang/gnn-re-ranking#1]
When will it be open source？

thanks！

**Comment by layumi** [comment]
Hi @QinZiwen 
Thanks a lot for your attention on our paper. 
We are currently discussing with Baidu Inc. about how to release the code. It may take a while to process the company admitting.

**Comment by layumi** [comment]
Hi @QinZiwen Thanks 
I closed this issue since the code is open to the community.
